AllCops:
  NewCops: enable

Style:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
